apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-dpl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:5.0.4
        command:
          - redis-server
          - "/etc/redis.d/redis.conf"
        ports:
        - containerPort: 6379
        resources:
          limits:
            cpu: "0.1"
            memory: 30Mi
        volumeMounts:
          - name: redis-data-storage
            mountPath: /data/redis
          - name: redis-config
            mountPath: /etc/redis.d
      volumes:
        - name: redis-data-storage
          hostPath:
            path: /data/redis
            type: Directory
        - name: redis-config
          configMap:
            name: redis-config
            items:
            - key: redis-config
              path: redis.conf