apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-dpl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:4.2
        command:
          - mongod
          - "-f"
          - "/etc/mongo.d/mongod.conf"
        ports:
        - containerPort: 27017
        resources:
          limits:
            cpu: "0.5"
            memory: 1Gi
        volumeMounts:
          - name: mongo-data-storage
            mountPath: /data/mongodb
          - name: mongo-config
            mountPath: /etc/mongo.d
      volumes:
        - name: mongo-data-storage
          hostPath:
            path: /data/mongodb
            type: Directory
        - name: mongo-config
          configMap:
            name: mongo-config
            items:
            - key: mongo-config
              path: mongod.conf